services:
    payment.stripe:
        class: PaymentBundle\Service\AppStripe
        arguments: ['%stripe%', '@doctrine.orm.entity_manager', '@security.token_storage']
    payment.stripe.subscription:
        class: PaymentBundle\Bridge\Stripe\StripeSubscription
        arguments: ['%stripe%', '@doctrine.orm.entity_manager', '@security.token_storage']
    payment.stripe.customer:
        class: PaymentBundle\Bridge\Stripe\StripeCustomer
        arguments: ['%stripe%', '@doctrine.orm.entity_manager', '@security.token_storage']
