services:
#    payment.example:
#        class: PaymentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.stripe:
        class: PaymentBundle\Service\AppStripe
        arguments: ['%stripe%', '@doctrine.orm.entity_manager', '@security.token_storage']
