<?php

namespace PaymentBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripeCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
