<?php

namespace AppBundle\Repository;

/**
 * StripePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripePlanRepository extends \Doctrine\ORM\EntityRepository
{
}
